FROM hashicorp/terraform:latest

# Install Azure CLI dependencies
RUN apk update && \
    apk add --no-cache \
    python3 \
    py3-pip \
    bash \
    ca-certificates \
    curl \
    openssh

# Install Azure CLI
RUN pip3 install --upgrade pip && \
    pip3 install azure-cli

WORKDIR /workspace