FROM hashicorp/terraform:latest

# Install Azure CLI
RUN apk add --no-cache \
    python3 \
    py3-pip \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    make

RUN pip3 install --upgrade pip && \
    pip3 install azure-cli

WORKDIR /workspace

ENTRYPOINT ["/bin/sh", "-c"]