version: '3.8'

services:
  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # REST Catalog for Iceberg
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=file:///tmp/warehouse/
      - CATALOG_URI=http://localhost:8181
      - CATALOG_IMPL=org.apache.iceberg.rest.RESTCatalog
      - CATALOG_IO_IMPL=org.apache.iceberg.io.FileIO
    volumes:
      - iceberg-warehouse:/tmp/warehouse
    restart: unless-stopped

  # Dremio CE for SQL Query Engine
  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047"  # Web UI
      - "31010:31010"  # ODBC/JDBC
      - "45678:45678"  # Inter-node communication
    volumes:
      - dremio-data:/opt/dremio/data
      - ./iceberg_lake/dremio/conf:/opt/dremio/conf
    environment:
      - DREMIO_MAX_MEMORY_GB=4
      - DREMIO_MAX_DIRECT_MEMORY_GB=8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9047/apiv2/server_status"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data:
  dremio-data:
  iceberg-warehouse: