version: '3.8'

services:
  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # REST Catalog for Iceberg
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3a://warehouse/
      - CATALOG_URI=http://iceberg-rest:8181
      - CATALOG_IMPL=org.apache.iceberg.rest.RESTCatalog
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
    depends_on:
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/v1/config"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Dremio CE for SQL Query Engine
  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047"  # Web UI
      - "31010:31010"  # ODBC/JDBC
      - "45678:45678"  # Inter-node communication
    volumes:
      - dremio-data:/opt/dremio/data
      - ./iceberg_lake/dremio/conf:/opt/dremio/conf
    environment:
      - DREMIO_MAX_MEMORY_GB=4
      - DREMIO_MAX_DIRECT_MEMORY_GB=8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9047/apiv2/server_status"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Initialize MinIO buckets and folders
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/warehouse;
      /usr/bin/mc policy set public myminio/warehouse;
      exit 0;
      "

volumes:
  minio-data:
  dremio-data: