        name: senti
        description: "A new Flutter project."
        publish_to: 'none'
        version: 1.0.0+1

        environment:
          sdk: '>=3.0.0 <4.0.0'

        dependencies:
          flutter:
            sdk: flutter
          logging: ^1.2.0
          provider: ^6.1.2
          intl: ^0.19.0
          fl_chart: ^0.68.0
          shared_preferences: ^2.2.3
          web_socket_channel: ^2.4.1
          http: ^1.2.1 # Add http package (use latest version)

          cupertino_icons: ^1.0.8

        dev_dependencies:
          flutter_test:
            sdk: flutter
          flutter_lints: ^5.0.0
          mockito: ^5.4.6
          build_runner: ^2.4.14

        flutter:
          uses-material-design: true
          # assets:
          #   - images/
        