global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    
  - job_name: 'sentiment-service'
    static_configs:
      - targets: ['sentiment-service:8080']
    
  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:8501']
    
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']