global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/alerts.yml"
  - "rules/recording_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8001']

  - job_name: 'sentiment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['sentiment-analysis:8000']
      
  - job_name: 'web-scraper'
    metrics_path: /metrics
    static_configs:
      - targets: ['web-scraper:8080']
      
  - job_name: 'clean-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['clean-metrics-proxy:8085']
      
  - job_name: 'subscription-receiver'
    metrics_path: /metrics
    static_configs:
      - targets: ['subscription-receiver:8080']
      
  - job_name: 'historical-scraper'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8083']
      
  - job_name: 'parquet-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8082']
    scrape_interval: 30s
    
  - job_name: 'test-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8083']
    scrape_interval: 15s
    
  - job_name: 'simple-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics-for-grafana:8084']
    scrape_interval: 5s
    
  - job_name: 'node-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']