name: Promote from SIT to UAT

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote'
        required: true
        default: 'latest'
  
  # Optionally, could be triggered on specific branch or tag
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'services/**'

# Add permissions at the top level
permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test_sit:
    name: Test SIT Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          if [ -f environments/sit/requirements.txt ]; then pip install -r environments/sit/requirements.txt; fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build services
        run: |
          cd infrastructure
          docker compose build
          docker compose up -d
      
      - name: Wait for services to start
        run: sleep 10
      
      - name: Run SIT environment tests
        run: |
          cd environments/sit/tests
          python -m pytest -xvs
      
      - name: Stop services
        run: |
          cd infrastructure
          docker compose down
  
  build_and_push:
    name: Build and Push Docker Images
    needs: test_sit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set lowercase repository name
        id: repo-name
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=${REPO_LC}" >> $GITHUB_ENV
      
      - name: Build and push Data Acquisition service
        uses: docker/build-push-action@v4
        with:
          context: ./services/data-acquisition
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/data-acquisition:${{ github.event.inputs.version }}
            ghcr.io/${{ env.REPO_LC }}/data-acquisition:latest
      
      # Add similar steps for other services as they are developed
  
  deploy_to_uat:
    name: Deploy to UAT Environment
    needs: build_and_push
    runs-on: ubuntu-latest
    environment: uat  # This requires manual approval in GitHub
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set lowercase repository name
        id: repo-name
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LC=${REPO_LC}" >> $GITHUB_ENV
      
      - name: Deploy to Azure with Terraform
        run: |
          # Configure environment variables for the deployment
          export GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          export GITHUB_USER=${{ github.actor }}
          export GITHUB_REPO=${{ env.REPO_LC }}
          export TF_VAR_location="westus"  # US West for low latency
          export ARM_SUBSCRIPTION_ID="644936a7-e58a-4ccb-a882-0005f213f5bd"
          export ARM_TENANT_ID="1ced8c49-a03c
