version: '3.8'

services:
  data-acquisition:
    build:
      context: ../services/data-acquisition
      dockerfile: Dockerfile
    image: rt-sentiment/data-acquisition:latest
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=sit
      - PORT=8002
    volumes:
      - ../services/data-acquisition/src:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - rt-sentiment-network

networks:
  rt-sentiment-network:
    driver: bridge